import {
  LayoutDashboard,
  Bot,
  Users,
  Calendar,
  Search,
  BookUser,
  Plug,
  Settings,
  LogOut,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Plus,
  Pencil,
  FileCog,
  MessageSquare,
  RefreshCw,
  MoreVertical,
  Paperclip,
  Mic,
  Send,
  Phone,
  Video,
  Power,
  BarChartHorizontal,
  FileText,
  Workflow,
  History,
  Info,
  Mail,
  Clock,
  Flag,
  Trash2,
  ArrowLeft,
  X,
  Settings2,
  AlertTriangle,
  Eye,
  CheckCircle,
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  AIAgent: Bot,
  CRM: Users,
  Appointments: Calendar,
  Prospecting: Search,
  Contacts: BookUser,
  Connection: Plug,
  Plug: Plug,
  Settings: Settings,
  Logout: LogOut,
  ChevronDown: ChevronDown,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  Plus: Plus,
  Pencil: Pencil,
  FileCog: FileCog,
  Conversations: MessageSquare,
  Refresh: RefreshCw,
  MoreVertical: MoreVertical,
  Paperclip: Paperclip,
  Mic: Mic,
  Send: Send,
  Phone: Phone,
  Video: Video,
  Power: Power,
  BarChart: BarChartHorizontal,
  FileText: FileText,
  Workflow: Workflow,
  History: History,
  Info: Info,
  Mail: Mail,
  Clock: Clock,
  Flag: Flag,
  Trash2: Trash2,
  ArrowLeft: ArrowLeft,
  X: X,
  Settings2: Settings2,
  AlertTriangle: AlertTriangle,
  Eye: Eye,
  Success: CheckCircle,
  Edit: Pencil,
};

export const Logo = () => (
  <div className="flex items-center space-x-2">
      <div className="w-8 h-8 bg-brand-yellow-dark rounded-md flex items-center justify-center">
          <div className="w-4 h-4 bg-gray-800 rounded-sm transform rotate-45" />
      </div>
      <span className="font-bold text-xl text-brand-text-primary">FLUOW AI</span>
  </div>
);